services:
  web:
    build:
      context: ./src
    ports:
      - '8000:8000'
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env
  elasticsearch:
    image: elasticsearch:8.8.0
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
volumes:
  postgres_data:
  esdata:
